package view.gui;
import java.io.*;
import java.nio.file.*;
import javax.swing.*;
import java.awt.Color;
import model.exceptions.InvalidDNIException;
import model.exceptions.InvalidDateException;
import model.validations.UserDataValidations;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author germanromort
 */
public class JFrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMaib
     */
    public JFrameMain() {
        initComponents();
        jLabelErrorName.setVisible(false);
        jLabelErrorDate.setVisible(false);
        jLabelErrorEmail.setVisible(false);
        jLabelErrorNif.setVisible(false);
        jLabelErrorCP.setVisible(false);
        jButtonCSV.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelImagen_Banner = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelTextoNombre = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelErrorName = new javax.swing.JLabel();
        jLabelErrorDate = new javax.swing.JLabel();
        jLabelTextoDate = new javax.swing.JLabel();
        jTextFieldDate = new javax.swing.JTextField();
        jLabelErrorEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelTextoEmail = new javax.swing.JLabel();
        jLabelErrorNif = new javax.swing.JLabel();
        jLabelTextoNif = new javax.swing.JLabel();
        jTextFieldNif = new javax.swing.JTextField();
        jLabelErrorCP = new javax.swing.JLabel();
        jLabelTextoCP = new javax.swing.JLabel();
        jTextFieldCP = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jButtonCSV = new javax.swing.JButton();
        jButtonValidate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabelTitulo.setText("VALIDADOR DE DATOS     German Romo");

        jLabelImagen_Banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/media/banner.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 255)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabelTextoNombre.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabelTextoNombre.setText("Nombre:");

        jTextFieldName.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabelErrorName.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabelErrorName.setText("DEBUG");

        jLabelErrorDate.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabelErrorDate.setText("DEBUG");

        jLabelTextoDate.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabelTextoDate.setText("Fecha:");

        jTextFieldDate.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateActionPerformed(evt);
            }
        });

        jLabelErrorEmail.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabelErrorEmail.setText("DEBUG");

        jTextFieldEmail.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabelTextoEmail.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabelTextoEmail.setText("Email:");

        jLabelErrorNif.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabelErrorNif.setText("DEBUG");

        jLabelTextoNif.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabelTextoNif.setText("NIF:");

        jTextFieldNif.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jTextFieldNif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNifActionPerformed(evt);
            }
        });

        jLabelErrorCP.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabelErrorCP.setText("DEBUG");

        jLabelTextoCP.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabelTextoCP.setText("CP:");

        jTextFieldCP.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jTextFieldCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelErrorCP, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorDate, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorNif, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelTextoCP)
                                .addGap(38, 38, 38)
                                .addComponent(jTextFieldCP))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelTextoDate)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDate))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelTextoEmail)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEmail))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelTextoNif)
                                .addGap(34, 34, 34)
                                .addComponent(jTextFieldNif))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelTextoNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(128, 128, 128))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldName)
                    .addComponent(jLabelTextoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorName)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTextoNif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorNif, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTextoEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorEmail)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTextoDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorDate, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTextoCP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelErrorCP, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButtonClear.setBackground(new java.awt.Color(255, 0, 102));
        jButtonClear.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonCSV.setBackground(new java.awt.Color(255, 0, 102));
        jButtonCSV.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jButtonCSV.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCSV.setText("CSV");
        jButtonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSVActionPerformed(evt);
            }
        });

        jButtonValidate.setBackground(new java.awt.Color(255, 0, 102));
        jButtonValidate.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jButtonValidate.setText("Validar");
        jButtonValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonValidate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelImagen_Banner, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonValidate, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelImagen_Banner, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidateActionPerformed
        int contadorCorrectas = 0;
        //-------------------------
        //COMPROBAR NOMBRE
        //-------------------------
        String name = jTextFieldName.getText();
        if (UserDataValidations.checkName(name)) {
            contadorCorrectas++;
            jLabelErrorName.setText("Nombre Correcto");
            jLabelErrorName.setVisible(true);
            jLabelErrorName.setForeground(Color.getHSBColor((float) 0.33, (float) 0.5, (float) 0.7));
            jTextFieldName.setEnabled(false);
        } else {

            jLabelErrorName.setText("Nombre Incorrecto");
            jLabelErrorName.setVisible(true);
            jLabelErrorName.setForeground(Color.RED);
        }
        //-------------------------
        //COMPROBAR FECHA
        //-------------------------

        String date = jTextFieldDate.getText();
boolean dateCorrecta = false;

try {
    UserDataValidations.checkDate(date);
    jLabelErrorDate.setText("Fecha válida");
    jLabelErrorDate.setVisible(true);
    jLabelErrorDate.setForeground(Color.getHSBColor(0.33f, 0.5f, 0.7f));
    dateCorrecta = true;
} catch (InvalidDateException e) {
    jLabelErrorDate.setText("Fecha incorrecta: " + e.getMessage());
    jLabelErrorDate.setVisible(true);
    jLabelErrorDate.setForeground(Color.RED);
}
if (nifCorrecto &&
    dateCorrecta &&
    UserDataValidations.checkZIP(cp) &&
    UserDataValidations.checkName(name) &&
    UserDataValidations.checkEmail(email)) {

    jButtonCSV.setEnabled(true);
    jButtonValidate.setEnabled(false);
} else {
    jButtonCSV.setEnabled(false);
    jButtonValidate.setEnabled(true);
}

        //-------------------------
        //COMPROBAR EMAIL
        //-------------------------

        String email = jTextFieldEmail.getText();
        if (UserDataValidations.checkEmail(email)) {
            contadorCorrectas++;
            jTextFieldEmail.setEnabled(false);

            jLabelErrorEmail.setText("Email Correcto");
            jLabelErrorEmail.setVisible(true);
            jLabelErrorEmail.setForeground(Color.getHSBColor((float) 0.33, (float) 0.5, (float) 0.7));
        } else {
            jLabelErrorEmail.setText("Email Incorrecto");
            jLabelErrorEmail.setVisible(true);
            jLabelErrorEmail.setForeground(Color.RED);
        }

        //-------------------------
        //COMPROBAR CP
        //-------------------------
        String cp = jTextFieldCP.getText().trim();
        if (UserDataValidations.checkZIP(cp)) {
            contadorCorrectas++;
            jTextFieldCP.setEnabled(false);

            jLabelErrorCP.setText("Código postal Correcto");
            jLabelErrorCP.setVisible(true);
            jLabelErrorCP.setForeground(Color.getHSBColor((float) 0.33, (float) 0.5, (float) 0.7));
        } else {
            jLabelErrorCP.setText("Código Postal Incorrecta");
            jLabelErrorCP.setVisible(true);
            jLabelErrorCP.setForeground(Color.RED);
        }

//-------------------------
// COMPROBAR NIF
//-------------------------
        String nif = jTextFieldNif.getText();
        boolean nifCorrecto = false;

        try {
            UserDataValidations.checkId(nif); // Si es inválido, lanza la excepción
            contadorCorrectas++;
            jTextFieldNif.setEnabled(false);
            jLabelErrorNif.setText("Documento Correcto");
            jLabelErrorNif.setVisible(true);
            jLabelErrorNif.setForeground(Color.getHSBColor((float) 0.33, (float) 0.5, (float) 0.7));
            nifCorrecto = true;
        } catch (InvalidDNIException e) {
            jLabelErrorNif.setText("Documento Incorrecto: " + e.getMessage());
            jLabelErrorNif.setVisible(true);
            jLabelErrorNif.setForeground(Color.RED);
        }

// Solo si el NIF y el resto de validaciones son correctas, se activan los botones
        if (nifCorrecto
                && UserDataValidations.checkZIP(cp)
                && UserDataValidations.checkName(name)
                && UserDataValidations.checkEmail(email)
                && UserDataValidations.checkDate(date)) {
            jButtonCSV.setEnabled(true);
            jButtonValidate.setEnabled(false);
        } else {
            jButtonCSV.setEnabled(false);
            jButtonValidate.setEnabled(true);
        }

    }//GEN-LAST:event_jButtonValidateActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed

        jButtonCSV.setEnabled(false);

        jTextFieldCP.setText("");
        jTextFieldCP.setEnabled(true);
        jLabelErrorCP.setVisible(false);

        jTextFieldDate.setText("");
        jTextFieldDate.setEnabled(true);
        jLabelErrorDate.setVisible(false);

        jTextFieldEmail.setText("");
        jTextFieldEmail.setEnabled(true);
        jLabelErrorEmail.setVisible(false);

        jTextFieldName.setText("");
        jTextFieldName.setEnabled(true);
        jLabelErrorName.setVisible(false);

        jTextFieldNif.setText("");
        jTextFieldNif.setEnabled(true);
        jLabelErrorNif.setVisible(false);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSVActionPerformed
        jButtonValidate.setEnabled(true);
        jButtonClear.setEnabled(true);
        
        String filePath = "datos.csv";
        File file = new File(filePath);    
    try {
        FileWriter fw = new FileWriter(file, true);
        PrintWriter pw = new PrintWriter(fw);
        
        pw.println(jTextFieldName.getText() + "," + jTextFieldNif.getText() + "," + jTextFieldEmail.getText() + "," + jTextFieldDate.getText() + "," + jTextFieldCP.getText());
        
        pw.close();
        fw.close();
        
        JOptionPane.showMessageDialog(this, "Datos guardados en CSV", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar en CSV", "Error", JOptionPane.ERROR_MESSAGE);
    }


    }//GEN-LAST:event_jButtonCSVActionPerformed

    private void jTextFieldCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPActionPerformed

    private void jTextFieldNifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNifActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonValidate;
    private javax.swing.JLabel jLabelErrorCP;
    private javax.swing.JLabel jLabelErrorDate;
    private javax.swing.JLabel jLabelErrorEmail;
    private javax.swing.JLabel jLabelErrorName;
    private javax.swing.JLabel jLabelErrorNif;
    private javax.swing.JLabel jLabelImagen_Banner;
    private javax.swing.JLabel jLabelTextoCP;
    private javax.swing.JLabel jLabelTextoDate;
    private javax.swing.JLabel jLabelTextoEmail;
    private javax.swing.JLabel jLabelTextoNif;
    private javax.swing.JLabel jLabelTextoNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldCP;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNif;
    // End of variables declaration//GEN-END:variables
}
